### PR TITLE
I want to verify my account on world coin

### PR DESCRIPTION
**Pull request by Samuelkatskamya**
Kamya Samuel Ssaazi verification for world coin

# {{Pull Request name here}}

## PR description

Please, give a brief description of what was changed or fixed and how you did it.

## Type

- [ ] Feature
- [ ] Refactoring
- [ ] Bugfix
- [ ] DevOps
- [ ] Testing

## Checklist

- [ ] I've made sure that my code works as expected by writing unit tests.
- [ ] I've checked if my code doesn't generate warnings or errors.
- [ ] I've performed a self-review of my code.
- [ ] I've made sure that my code follows the style guidelines of the project.
- [ ] I've commented hard-to-understand parts of my code.
- [ ] I've made appropriate changes in the documentation.

### CODE REVIEW

**Comment by Samuelkatskamya** [comment]
I want to verify my world 🌍 coin

**Comment by Samuelkatskamya** [comment]
I want to verify my world 🌍 coin

**Comment by wiktorlazarski** [comment]
Hey @Samuelkatskamya, 

thanks for your contribution. Can you elaborate more on the purpose of this PR and why you'd like to have it merged (preferably by fulfilling PR template above 😉)? 

Thanks in advance.
Best regards,
Wiktor

**Comment by KenBrown10** [comment]
⭐️🌟⭐️🌟⭐️🌟⭐️🌟⭐️🌟⭐️

**Comment by TanguyJeanneau** [comment]
Hi @Samuelkatskamya !

In the absence of further activity, we are closing this PR.

If you are looking to get your World ID verified, you can have a look [here](https://worldcoin.org/find-orb) to find your nearest Orb and visit it.

Have a great day !
Tanguy

**Pull request closed without merging**
